In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

In [3]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)

        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)

        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        x[idx] = tmp_val
        it.iternext()

    return grad

In [4]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        self.xdata = xdata.reshape(4, 2)
        self.tdata = tdata.reshape(4, 1)
        self.W = np.random.rand(self.xdata.shape[1], 1)
        self.b = np.random.rand(1)
        self.learning_rate = 1e-2

    def loss_func(self):
        delta = 1e-7
        z = np.dot(self.xdata, self.W) + self.b
        y = sigmoid(z)
        return -np.sum(self.tdata * np.log(y + delta) + (1 - self.tdata) * np.log((1 - y) + delta))

    def train(self):
        f = lambda x : self.loss_func()
        print("Initial loss value = ", self.loss_func())
        for step in range(8001):
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
            if (step % 1000 == 0):
                print("step = ", step, "loss value = ", self.loss_func())

    def predict(self, test_data):
        z = np.dot(test_data, self.W) + self.b
        y = sigmoid(z)
        if y >= 0.5:
            result = 1
        else:
            result = 0
            
        return y, result

    def accuracy(self, test_xdata, test_tdata):
        matched_list = []
        not_matched_list = []
        for index in range(len(xdata)):
            (real_val, logical_val) = self.predict(test_xdata[index])
            if logical_val == test_tdata[index]:
                matched_list.append(index)
            else:
                not_matched_list.append(index)
        accuracy_val = len(matched_list) / len(test_xdata)
        return accuracy_val

In [5]:
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 0, 0, 1])
AND_obj = LogicGate("AND_GATE", xdata, tdata)
AND_obj.train()

Initial loss value =  4.41254555431711
step =  0 loss value =  4.356985100078407
step =  1000 loss value =  1.004977366665566
step =  2000 loss value =  0.6594317348159655
step =  3000 loss value =  0.4909493435450939
step =  4000 loss value =  0.3899769211916553
step =  5000 loss value =  0.3227014564797928
step =  6000 loss value =  0.2747543244865454
step =  7000 loss value =  0.2389187314793496
step =  8000 loss value =  0.21116309086000157


In [6]:
test_xdata = np.array([ [0,0], [0,1], [1,0], [1,1] ])
for input_data in test_xdata:
    (sigmoid_val, logical_val) = AND_obj.predict(input_data)
    print(input_data, " = ", logical_val)
    print(input_data, " = ", sigmoid_val)
print('--------------------------')
test_tdata = np.array([0, 0, 0, 1])
accuracy_ret = AND_obj.accuracy(test_xdata, test_tdata)
print('Accuracy => ', accuracy_ret)

[0 0]  =  0
[0 0]  =  [0.0003694]
[0 1]  =  0
[0 1]  =  [0.05973536]
[1 0]  =  0
[1 0]  =  [0.05973523]
[1 1]  =  1
[1 1]  =  [0.91612143]
--------------------------
Accuracy =>  1.0


In [7]:
xdata = np.array([ [0,0],[0,1],[1,0],[1,1]])
tdata = np.array([0,1,1,1])
OR_obj = LogicGate("OR GATE",xdata,tdata)
OR_obj.train()

Initial loss value =  1.8048833223888323
step =  0 loss value =  1.7999007494167807
step =  1000 loss value =  0.6941247653247334
step =  2000 loss value =  0.4216546040798512
step =  3000 loss value =  0.29850824759473965
step =  4000 loss value =  0.22947578960529727
step =  5000 loss value =  0.18570650299059346
step =  6000 loss value =  0.15563229869518608
step =  7000 loss value =  0.13376434093479406
step =  8000 loss value =  0.11718135668817034


In [8]:
test_xdata = np.array([ [0,0], [0,1], [1,0], [1,1] ])
for input_data in test_xdata:
    (sigmoid_val, logical_val) = OR_obj.predict(input_data)
    print(input_data, " = ", logical_val)
    print(input_data, " = ", sigmoid_val)
print('--------------------------')
test_tdata = np.array([0, 1, 1, 1])
accuracy_ret = OR_obj.accuracy(test_xdata, test_tdata)
print('Accuracy => ', accuracy_ret)

[0 0]  =  0
[0 0]  =  [0.06369498]
[0 1]  =  1
[0 1]  =  [0.97472453]
[1 0]  =  1
[1 0]  =  [0.97460653]
[1 1]  =  1
[1 1]  =  [0.99995404]
--------------------------
Accuracy =>  1.0


In [9]:
xdata = np.array([ [0,0],[0,1],[1,0],[1,1]])
tdata = np.array([1,1,1,0])
NAND_obj = LogicGate("NAND GATE",xdata,tdata)
NAND_obj.train()

Initial loss value =  2.9849239880637137
step =  0 loss value =  2.97935291701313
step =  1000 loss value =  1.085858235209243
step =  2000 loss value =  0.6922160842530609
step =  3000 loss value =  0.5090744600794093
step =  4000 loss value =  0.4014947450780016
step =  5000 loss value =  0.33065148945752854
step =  6000 loss value =  0.2805587464439807
step =  7000 loss value =  0.2433344500321421
step =  8000 loss value =  0.21463002209892643


In [10]:
test_xdata = np.array([ [0,0], [0,1], [1,0], [1,1] ])
for input_data in test_xdata:
    (sigmoid_val, logical_val) = NAND_obj.predict(input_data)
    print(input_data, " = ", logical_val)
    print(input_data, " = ", sigmoid_val)
print('--------------------------')
test_tdata = np.array([1, 1, 1, 0])
accuracy_ret = NAND_obj.accuracy(test_xdata, test_tdata)
print('Accuracy => ', accuracy_ret)

[0 0]  =  1
[0 0]  =  [0.99961153]
[0 1]  =  1
[0 1]  =  [0.93932504]
[1 0]  =  1
[1 0]  =  [0.93932563]
[1 1]  =  0
[1 1]  =  [0.08520485]
--------------------------
Accuracy =>  1.0


In [11]:
xdata = np.array([ [0,0],[0,1],[1,0],[1,1]])
tdata = np.array([0,1,1,0])
XOR_obj = LogicGate("XOR GATE",xdata,tdata)
XOR_obj.train()

Initial loss value =  3.5353069924753444
step =  0 loss value =  3.5163811109614613
step =  1000 loss value =  2.7727801605248006
step =  2000 loss value =  2.7725909310327803
step =  3000 loss value =  2.772588016005879
step =  4000 loss value =  2.772587926016016
step =  5000 loss value =  2.772587922399783
step =  6000 loss value =  2.7725879222466903
step =  7000 loss value =  2.7725879222401533
step =  8000 loss value =  2.7725879222398744


In [12]:
test_xdata = np.array([ [0,0], [0,1], [1,0], [1,1] ])
for input_data in test_xdata:
    (sigmoid_val, logical_val) = XOR_obj.predict(input_data)
    print(input_data, " = ", logical_val)
    print(input_data, " = ", sigmoid_val)
print('--------------------------')
test_tdata = np.array([0, 1, 1, 0])
accuracy_ret = XOR_obj.accuracy(test_xdata, test_tdata)
print('Accuracy => ', accuracy_ret)

[0 0]  =  1
[0 0]  =  [0.50000006]
[0 1]  =  1
[0 1]  =  [0.50000001]
[1 0]  =  1
[1 0]  =  [0.50000001]
[1 1]  =  0
[1 1]  =  [0.49999996]
--------------------------
Accuracy =>  0.75


In [13]:
input_data = np.array([ [0,0], [0,1], [1,0], [1,1] ])

s1 = []
s2 = []
new_input_data = []
final_output = []

for index in range(len(input_data)):
    s1 = NAND_obj.predict(input_data[index])
    s2 = OR_obj.predict(input_data[index])
    new_input_data.append(s1[-1])
    new_input_data.append(s2[-1])
    (sigmoid_val, logical_val) = AND_obj.predict(np.array(new_input_data))
    final_output.append(logical_val)
    new_input_data = []

for index in range(len(input_data)):
    print(input_data[index], " = ", final_output[index])

[0 0]  =  0
[0 1]  =  1
[1 0]  =  1
[1 1]  =  0


In [14]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)

        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x)

        grad[idx] = (fx1 - fx2) / (2 * delta_x)
        x[idx] = tmp_val
        it.iternext()

    return grad

In [23]:
class LogicGate:
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        self.xdata = xdata.reshape(4, 2)
        self.tdata = tdata.reshape(4, 1)
        
        self.W2 = np.random.rand(2, 5)
        self.W3 = np.random.rand(5, 2)
        self.W4 = np.random.rand(2, 1)

        self.b2 = np.random.rand(5)
        self.b3 = np.random.rand(2)
        self.b4 = np.random.rand(1)
        
        # self.learning_rate = 10
        self.learning_rate = 0.05

    def feed_forward(self):
        delta = 1e-7
        z2 = np.dot(self.xdata, self.W2) + self.b2
        a2 = sigmoid(z2)
        z3 = np.dot(a2, self.W3) + self.b3
        a3 = sigmoid(z3)
        z4 = np.dot(a3, self.W4) + self.b4
        y = a4 = sigmoid(z4)
        return -np.sum(self.tdata * np.log(y + delta) + (1 - self.tdata) * np.log((1 - y) + delta))

    def feed_forward_print(self):
        delta = 1e-7
        z2 = np.dot(self.xdata, self.W2) + self.b2
        print("z2 => ", z2)
        a2 = sigmoid(z2)
        z3 = np.dot(a2, self.W3) + self.b3
        print("z3 => ", z3)
        a3 = sigmoid(z3)
        z4 = np.dot(a3, self.W4) + self.b4
        print("z4 => ", z4)
        y = a4 = sigmoid(z4)
        return -np.sum(self.tdata * np.log(y + delta) + (1 - self.tdata) * np.log((1 - y) + delta))

    def train(self):
        f = lambda x : self.feed_forward()
        print("Initial loss value = ", self.feed_forward())
        
        for step in range(7001):
            self.W2 -= self.learning_rate * numerical_derivative(f, self.W2)
            self.b2 -= self.learning_rate * numerical_derivative(f, self.b2)
            
            self.W3 -= self.learning_rate * numerical_derivative(f, self.W3)
            self.b3 -= self.learning_rate * numerical_derivative(f, self.b3)

            self.W4 -= self.learning_rate * numerical_derivative(f, self.W4)
            self.b4 -= self.learning_rate * numerical_derivative(f, self.b4)
            
            if (step % 1000 == 0):
                print("step = ", step, "loss value = ", self.feed_forward_print())

    def predict(self, input_data):
        self.xdata = input_data
        z2 = np.dot(self.xdata, self.W2) + self.b2
        a2 = sigmoid(z2)
        z3 = np.dot(a2, self.W3) + self.b3
        a3 = sigmoid(z3)
        z4 = np.dot(a3, self.W4) + self.b4
        y = a4 = sigmoid(z4)
        
        if y >= 0.5:
            result = 1
        else:
            result = 0
            
        return y, result

In [24]:
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 1, 1, 0])

xor_obj = LogicGate("XOR", xdata, tdata)
xor_obj.train()

Initial loss value =  4.0083964997360635
z2 =>  [[0.96815216 0.89192463 0.32416584 0.03678995 0.05952742]
 [1.04725677 1.62282801 0.83874766 0.38453013 0.98994392]
 [1.30600681 1.69594601 1.28743978 0.86177156 0.08235938]
 [1.38511143 2.42684939 1.8020216  1.20951174 1.01277588]]
z3 =>  [[1.68655284 3.13505012]
 [2.03234779 3.46803665]
 [1.93197808 3.60951084]
 [2.22652893 3.86245605]]
z4 =>  [[1.44332821]
 [1.48243178]
 [1.47712345]
 [1.50352306]]
step =  0 loss value =  3.7698825278332677
z2 =>  [[0.95852203 0.86528113 0.29868996 0.02480646 0.03011742]
 [1.05170757 1.62900269 0.88622983 0.4209401  0.99081973]
 [1.30350799 1.70187738 1.31175673 0.88423671 0.14824105]
 [1.39669353 2.46559893 1.8992966  1.28037036 1.10894336]]
z3 =>  [[1.55527425 3.04982677]
 [1.92679398 3.41117363]
 [1.8427319  3.5480291 ]
 [2.14701533 3.81436656]]
z4 =>  [[-0.01676093]
 [ 0.0073141 ]
 [ 0.00369096]
 [ 0.01956092]]
step =  1000 loss value =  2.76857672576315
z2 =>  [[ 0.95104101  0.81655232  0.2543272 

In [25]:
test_data = np.array([[0,0], [0,1], [1,0], [1,1]])
for data in test_data:
    sigmoid_val, logical_val = xor_obj.predict(data)
    print(data, " = ", logical_val)

[0 0]  =  0
[0 1]  =  1
[1 0]  =  1
[1 1]  =  0


In [18]:


class Logicgate_MLP:
    def __init__(self, gate_name, xdata, tdata, hidden1_nodes=4, hidden2_nodes=2):
        self.name = gate_name
        self.xdata = xdata.reshape(4, 2)
        self.tdata = tdata.reshape(4, 1)
        # 은닉층1 가중치 및 편향 초기화
        self.hidden1_nodes = hidden1_nodes
        self.W1 = np.random.randn(2, hidden1_nodes)  # 2개의 입력, hidden1_nodes개의 은닉 노드
        self.b1 = np.random.randn(hidden1_nodes)
        # 은닉층2 가중치 및 편향 초기화
        self.hidden2_nodes = hidden2_nodes
        self.W2 = np.random.randn(hidden1_nodes, hidden2_nodes)  # hidden1_nodes개의 은닉 노드, hidden2_nodes개의 은닉 노드
        self.b2 = np.random.randn(hidden2_nodes)
        # 출력층 가중치 및 편향 초기화
        self.W3 = np.random.randn(hidden2_nodes, 1)  # hidden2_nodes 개의 은닉 노드, 1개의 출력 노드
        self.b3 = np.random.randn(1)
        self.learning_rate = 1e-2
    def feed_forward(self, xdata):
        z1 = np.dot(xdata, self.W1) + self.b1
        a1 = sigmoid(z1)
        z2 = np.dot(a1, self.W2) + self.b2
        a2 = sigmoid(z2)
        z3 = np.dot(a2, self.W3) + self.b3
        y = sigmoid(z3)
        return y
    def loss_func(self, y):
        delta = 1e-7
        return -np.sum(self.tdata*np.log(y+delta)+(1-self.tdata)*np.log((1-y)+delta))
        
        return -np.sum(self.tdata * np.log(y + delta) + (1 - self.tdata) * np.log((1 - y) + delta))
        
        
    def train(self):
        f = lambda x: self.loss_func(self.feed_forward(self.xdata))
        print("Initial loss value = ", self.loss_func(self.feed_forward(self.xdata)))
        for step in range(20001):
            self.W1 -= self.learning_rate * numerical_derivative(f, self.W1)
            self.b1 -= self.learning_rate * numerical_derivative(f, self.b1)
            self.W2 -= self.learning_rate * numerical_derivative(f, self.W2)
            self.b2 -= self.learning_rate * numerical_derivative(f, self.b2)
            self.W3 -= self.learning_rate * numerical_derivative(f, self.W3)
            self.b3 -= self.learning_rate * numerical_derivative(f, self.b3)
            if (step % 1000 == 0):
                print("step = ", step, "loss value = ", self.loss_func(self.feed_forward(self.xdata)))
    def predict(self, input_data):
        y = self.feed_forward(input_data)
        if y > 0.5:
            result = 1
        else:
            result = 0
        return y, result


In [19]:
# 학습 데이터
xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
tdata = np.array([0, 1, 1, 0]) # XOR 데이터
# 모델 생성
XOR_obj = Logicgate_MLP("XOR", xdata, tdata, hidden1_nodes=4, hidden2_nodes=2)
XOR_obj.train()
# 테스트 데이터
test_xdata = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for input_data in test_xdata:
    (sigmoid_val, logical_val) = XOR_obj.predict(input_data.reshape(1, 2))
    print(input_data, " = ", logical_val)

Initial loss value =  5.053716796952118
step =  0 loss value =  4.99297731114802
step =  1000 loss value =  2.721798912772436
step =  2000 loss value =  2.66051109305728
step =  3000 loss value =  2.527430485395282
step =  4000 loss value =  2.3153709119804136
step =  5000 loss value =  2.1170790445794117
step =  6000 loss value =  1.9373063636629306
step =  7000 loss value =  1.3635504769118052
step =  8000 loss value =  0.596286200193133
step =  9000 loss value =  0.27757107874614617
step =  10000 loss value =  0.16068346363516905
step =  11000 loss value =  0.10771168127553363
step =  12000 loss value =  0.07914842441320935
step =  13000 loss value =  0.061771729090964775
step =  14000 loss value =  0.050266641220513546
step =  15000 loss value =  0.042165423226165434
step =  16000 loss value =  0.036190203099653706
step =  17000 loss value =  0.03162143367071645
step =  18000 loss value =  0.02802640400516964
step =  19000 loss value =  0.025130792823701675
step =  20000 loss value

In [20]:
np.random.rand(2, 4)

array([[0.02918861, 0.11138822, 0.81342188, 0.66411931],
       [0.32125958, 0.17594783, 0.10001365, 0.41449162]])