## RNN

In [4]:
from keras.models import Sequential
from keras.layers import SimpleRNN

model = Sequential()
# model.add(SimpleRNN(3, input_shape = (2, 10)))
model.add(SimpleRNN(3, input_length = 2, input_dim = 10))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (None, 3)                 42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [2]:
from keras.models import Sequential
from keras.layers import SimpleRNN
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape = (8, 2, 10)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (8, 3)                    42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [3]:
from keras.models import Sequential
from keras.layers import SimpleRNN
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape = (8, 2, 10), return_sequences=True)) #return_sequences=True인 경우
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (8, 2, 3)                 42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [5]:
import numpy as np
inputs = np.random.random((8, 2, 10))
model = Sequential()
model.add(SimpleRNN(3))
model(inputs)
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (8, 3)                    42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
import numpy as np
inputs = np.random.random((8, 2, 10))
model = Sequential()
model.add(SimpleRNN(3, return_sequences=True))
model(inputs)
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_5 (SimpleRNN)    (8, 2, 3)                 42        
                                                                 
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### RNN 이용해서 텍스트 생성

In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [8]:
text = """경마장에 있는 말이 뛰고 있다\n그의 말이 법이다\n가는 말이 고와야 오는 말이 곱다"""

In [9]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
print("단어 집합의 크기 : %d" % vocab_size)

단어 집합의 크기 : 12


In [10]:
t.word_index

{'말이': 1,
 '경마장에': 2,
 '있는': 3,
 '뛰고': 4,
 '있다': 5,
 '그의': 6,
 '법이다': 7,
 '가는': 8,
 '고와야': 9,
 '오는': 10,
 '곱다': 11}

In [11]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print("학습이 사용할 샘플의 개수 : %d" % len(sequences))

학습이 사용할 샘플의 개수 : 11


In [16]:
t.texts_to_sequences([text.split('\n')[0]])

[[2, 3, 1, 4, 5]]

In [17]:
max_len = max(len(l) for l in sequences)


In [18]:
sequences = pad_sequences(sequences, maxlen = max_len, padding = 'pre')
sequences

array([[ 0,  0,  0,  0,  2,  3],
       [ 0,  0,  0,  2,  3,  1],
       [ 0,  0,  2,  3,  1,  4],
       [ 0,  2,  3,  1,  4,  5],
       [ 0,  0,  0,  0,  6,  1],
       [ 0,  0,  0,  6,  1,  7],
       [ 0,  0,  0,  0,  8,  1],
       [ 0,  0,  0,  8,  1,  9],
       [ 0,  0,  8,  1,  9, 10],
       [ 0,  8,  1,  9, 10,  1],
       [ 8,  1,  9, 10,  1, 11]])

In [19]:
# sequences = np.array(sequences)

X = sequences[:, :-1]
y = sequences[:, -1]

In [20]:
X

array([[ 0,  0,  0,  0,  2],
       [ 0,  0,  0,  2,  3],
       [ 0,  0,  2,  3,  1],
       [ 0,  2,  3,  1,  4],
       [ 0,  0,  0,  0,  6],
       [ 0,  0,  0,  6,  1],
       [ 0,  0,  0,  0,  8],
       [ 0,  0,  0,  8,  1],
       [ 0,  0,  8,  1,  9],
       [ 0,  8,  1,  9, 10],
       [ 8,  1,  9, 10,  1]])

In [22]:
y

array([ 3,  1,  4,  5,  1,  7,  1,  9, 10,  1, 11])

In [23]:
y = to_categorical(y, num_classes = vocab_size)
y

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [25]:
model = Sequential()
model.add(Embedding(vocab_size, 6, input_length = max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 6)              72        
                                                                 
 simple_rnn_6 (SimpleRNN)    (None, 32)                1248      
                                                                 
 dense (Dense)               (None, 12)                396       
                                                                 
Total params: 1716 (6.70 KB)
Trainable params: 1716 (6.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model = Sequential()
model.add(Embedding(vocab_size, 6))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.build(input_shape = (None, max_len-1))
model.summary() # tensorflow 2.16 이상 버전에서는 이 형식만 가능

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 6)           72        
                                                                 
 simple_rnn_7 (SimpleRNN)    (None, 32)                1248      
                                                                 
 dense_1 (Dense)             (None, 12)                396       
                                                                 
Total params: 1716 (6.70 KB)
Trainable params: 1716 (6.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, y, epochs = 200, verbose = 2)


Epoch 1/200


1/1 - 4s - loss: 2.4902 - accuracy: 0.0000e+00 - 4s/epoch - 4s/step
Epoch 2/200
1/1 - 0s - loss: 2.4787 - accuracy: 0.0000e+00 - 16ms/epoch - 16ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4672 - accuracy: 0.0000e+00 - 11ms/epoch - 11ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4557 - accuracy: 0.1818 - 9ms/epoch - 9ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4440 - accuracy: 0.1818 - 12ms/epoch - 12ms/step
Epoch 6/200
1/1 - 0s - loss: 2.4320 - accuracy: 0.2727 - 11ms/epoch - 11ms/step
Epoch 7/200
1/1 - 0s - loss: 2.4196 - accuracy: 0.3636 - 12ms/epoch - 12ms/step
Epoch 8/200
1/1 - 0s - loss: 2.4068 - accuracy: 0.3636 - 5ms/epoch - 5ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3934 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3794 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3647 - accuracy: 0.3636 - 13ms/epoch - 13ms/step
Epoch 12/200
1/1 - 0s - loss: 2.3493 - accuracy: 0.3636 - 10ms/epoch - 10ms/step
Epoch 13/200
1/1 - 0s - loss: 2.33

In [29]:
def sentence_generation(model, t, current_word, n):
    # init_word = current_word
    sentence=  ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen = max_len-1, padding = 'pre')
        temp = model.predict(encoded)
        result = np.argmax(temp, axis = 1)
        for word, index in t.word_index.items():
            if index == result:
                break

        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word

    # sentence = init_word + sentence
    sentence = current_word
    return sentence
    

In [33]:
print(sentence_generation(model, t, '말이', 10))

1/1 [==============================] - 0s 64ms/step
말이 말이 법이다 말이 말이 말이 말이 곱다 말이 말이 말이


#### LSTM을 이용하여 텍스트 생성

In [35]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [36]:
df = pd.read_csv("ArticlesApril2018.csv")
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324 entries, 0 to 1323
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   articleID         1324 non-null   object
 1   articleWordCount  1324 non-null   int64 
 2   byline            1324 non-null   object
 3   documentType      1324 non-null   object
 4   headline          1324 non-null   object
 5   keywords          1324 non-null   object
 6   multimedia        1324 non-null   int64 
 7   newDesk           1324 non-null   object
 8   printPage         1324 non-null   int64 
 9   pubDate           1324 non-null   object
 10  sectionName       1324 non-null   object
 11  snippet           1324 non-null   object
 12  source            1324 non-null   object
 13  typeOfMaterial    1324 non-null   object
 14  webURL            1324 non-null   object
dtypes: int64(3), object(12)
memory usage: 155.3+ KB


In [37]:
print("열의 개수: ", len(df.columns))
df.columns

열의 개수:  15


Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')

In [39]:
df['headline'].isnull().values.any()

False

In [40]:
headline = []
# 헤드라인의 값들을 리스트로 저장
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [41]:
print('총 샘플의 개수 : {}'.format(len(headline)))

총 샘플의 개수 : 1324


In [43]:
headline = [word for word in headline if word != "Unknown"]
print('노이즈값 제거 후 샘플의 개수 : {}'.format(len(headline)))

노이즈값 제거 후 샘플의 개수 : 1214


In [44]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [50]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [48]:
def repreprocessing(s):
    s = s.encode("utf8").decode("ascii", "ignore")
    return ''.join(c for c in s if c not in punctuation).lower()


In [49]:
text = [repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [53]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print("단어 집합의 크기 : %d" % vocab_size)

단어 집합의 크기 : 3494


In [58]:
t.word_index

{'the': 1,
 'a': 2,
 'to': 3,
 'of': 4,
 'in': 5,
 'for': 6,
 'and': 7,
 'is': 8,
 'on': 9,
 'with': 10,
 'trump': 11,
 'as': 12,
 'at': 13,
 'new': 14,
 'how': 15,
 'from': 16,
 'it': 17,
 'an': 18,
 'that': 19,
 'be': 20,
 'season': 21,
 'us': 22,
 'you': 23,
 'its': 24,
 'what': 25,
 'episode': 26,
 'can': 27,
 'your': 28,
 'not': 29,
 'he': 30,
 'now': 31,
 'his': 32,
 'are': 33,
 'teaching': 34,
 'war': 35,
 'out': 36,
 'no': 37,
 'was': 38,
 'by': 39,
 'trumps': 40,
 'has': 41,
 'over': 42,
 'may': 43,
 'into': 44,
 'why': 45,
 'more': 46,
 'we': 47,
 'who': 48,
 'about': 49,
 'recap': 50,
 'activities': 51,
 '1': 52,
 'just': 53,
 'do': 54,
 'women': 55,
 'when': 56,
 'syria': 57,
 'trade': 58,
 'i': 59,
 '2': 60,
 'or': 61,
 'will': 62,
 'this': 63,
 'have': 64,
 'president': 65,
 'but': 66,
 'home': 67,
 'up': 68,
 'long': 69,
 'one': 70,
 'off': 71,
 'facebook': 72,
 'house': 73,
 'gop': 74,
 'our': 75,
 'case': 76,
 'they': 77,
 'life': 78,
 'end': 79,
 'right': 80,
 'some':

In [61]:
sequences = list()
for line in text:
    #print(t.texts_to_sequences([line]))
    encoded = t.texts_to_sequences([line])[0]
    # print(encoded)
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        # print(sequence)
        sequences.append(sequence)
        
print("학습에 사용할 샘플의 개수: %d" % len(sequences))

학습에 사용할 샘플의 개수: 7803


In [62]:
sequence

[170, 8, 3493, 115, 2, 1025]

In [63]:
max_len = max(len(l) for l in sequences)
print("샘플의 최대 길이 : {}".format(max_len))

샘플의 최대 길이 : 24


In [64]:
sequences = pad_sequences(sequences, maxlen = max_len, padding = 'pre')

In [65]:
sequences

array([[   0,    0,    0, ...,    0,   99,  269],
       [   0,    0,    0, ...,   99,  269,  371],
       [   0,    0,    0, ...,  269,  371, 1115],
       ...,
       [   0,    0,    0, ...,    8, 3493,  115],
       [   0,    0,    0, ..., 3493,  115,    2],
       [   0,    0,    0, ...,  115,    2, 1025]])

In [66]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

In [67]:
y = to_categorical(y, num_classes = vocab_size)
y[1]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [76]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM, Bidirectional

In [77]:
model = Sequential()
model.add(Embedding(vocab_size, 100))
model.add(Bidirectional(LSTM(128)))
model.add(Dense(vocab_size, activation = 'softmax'))
model.build(input_shape = (None, max_len-1))
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, None, 100)         349400    
                                                                 
 bidirectional (Bidirection  (None, 256)               234496    
 al)                                                             
                                                                 
 dense_4 (Dense)             (None, 3494)              897958    
                                                                 
Total params: 1481854 (5.65 MB)
Trainable params: 1481854 (5.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [79]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=30, verbose=2)

Epoch 1/30
244/244 - 20s - loss: 6.3827 - accuracy: 0.0675 - 20s/epoch - 82ms/step
Epoch 2/30
244/244 - 12s - loss: 5.9633 - accuracy: 0.0786 - 12s/epoch - 49ms/step
Epoch 3/30
244/244 - 11s - loss: 5.5902 - accuracy: 0.0891 - 11s/epoch - 45ms/step
Epoch 4/30
244/244 - 12s - loss: 5.2233 - accuracy: 0.1014 - 12s/epoch - 48ms/step
Epoch 5/30
244/244 - 11s - loss: 4.8648 - accuracy: 0.1225 - 11s/epoch - 47ms/step
Epoch 6/30
244/244 - 11s - loss: 4.5217 - accuracy: 0.1579 - 11s/epoch - 44ms/step
Epoch 7/30
244/244 - 11s - loss: 4.1834 - accuracy: 0.2042 - 11s/epoch - 44ms/step
Epoch 8/30
244/244 - 11s - loss: 3.8504 - accuracy: 0.2653 - 11s/epoch - 46ms/step
Epoch 9/30
244/244 - 11s - loss: 3.5091 - accuracy: 0.3333 - 11s/epoch - 45ms/step
Epoch 10/30
244/244 - 11s - loss: 3.1642 - accuracy: 0.3975 - 11s/epoch - 45ms/step
Epoch 11/30
244/244 - 11s - loss: 2.8150 - accuracy: 0.4633 - 11s/epoch - 45ms/step
Epoch 12/30
244/244 - 11s - loss: 2.4743 - accuracy: 0.5302 - 11s/epoch - 45ms/step
E

In [80]:
def sentence_generation(model, t, current_word, n):
    # init_word = current_word
    sentence=  ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen = max_len-1, padding = 'pre')
        temp = model.predict(encoded)
        result = np.argmax(temp, axis = 1)
        for word, index in t.word_index.items():
            if index == result:
                break

        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word

    # sentence = init_word + sentence
    sentence = current_word
    return sentence
    

In [81]:
print(sentence_generation(model, t, 'i', 10))

1/1 [==============================] - 0s 49ms/step
i disapprove of school vouchers can i still apply for them
